INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (3,10,'Check out their website.',8,'CMG Information Services','ZDmBZPgRWncX1lwavirML4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (8,17,'No response.',10,'Morgan Stanley','mlMdUJWW5xzFjgobzOfpEV4VndTHx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (14,2,'Out of the office.',3,'Tesco','i7uqS1mgatF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (18,10,NULL,7,'Van Tonen Constructies','uN2ZdJYzpXCNEKnl6TqIvIYUpuS8xPYmna3DTsS7A1Zx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (22,18,NULL,2,'MerckSharp&Dohme','GSU67zogwFY5pdlDyVRvAQngrc');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (25,21,'Must send an email.',3,'Datanamic Solutions BV','xDWwekrq2MgIFyFOdAHMCWvbPMZyCpibmW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (35,22,NULL,5,'Djingy Media','UwjOtrNaGbw6PuFC2qDY5le0Fy2Tsan');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (41,25,'We need to investigate this.',9,'Allen&Hanburys Ltd','AhWuLWSCjAKW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (42,33,'Single mode turned off.',8,'Numicom','ThK4yiEEYB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (51,43,'We must investigate this.',10,'Nongy Services','gEg');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (52,51,'No longer used.',9,'BLogic','HBa01hQfNo1gNu');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (57,56,'Expert mode turned off.',1,'Global Village Communication','dI0qmfkv0BFfSaIa6ox1nLdwlpv0t360h4bdMsQWJF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (60,58,'Missed his call.',7,'Sun Microsystems','yuNvF8Yxm0XdClxBv55PhYhs0awJWzaW6uL2jhBcj3glb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (67,64,'Find more on the website.',7,'EMI Music','v5luRPD7KPsA3BX');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (74,71,'Must verify this entry.',6,'Schering','GsmMYWMXBbej2mMoVjGVnQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (84,73,'All modifications are cancelled',10,'Van Tonen Advies','z');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (90,79,'All modifications are cancelled',5,'Zeneca','hUK1bGKPrXZMUnt');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (99,86,'Check out their website.',10,'V&D','WwleEOH64NxexqjLI7tIN5vnv78Zi');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (108,95,'A quick note.',2,'Fenomen','XHuda47kEAeVXpsgzJpy');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (115,96,NULL,5,'OneTechnology','S8V6ebTWqv0LzTjGqdRi');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (122,104,'Single mode turned on.',3,'Camelot','sQqbLhHgae2xN6DqEIs3XE');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (132,111,NULL,9,'Pfizer','vRd3GGCxvaEgQpwhvSBbl3ZAj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (141,119,NULL,9,'Sapanda.com','grlPogHvOx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (144,122,NULL,6,'Compuserve','k2ZR8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (149,130,'Just a note.',2,'Open Market','fSUg');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (154,133,'All modifications are cancelled',7,'DenmarkAero','o');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (162,142,NULL,7,'Van Meten Constructies','ThnSSR2fs6sX14mmJpitiG6U');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (163,145,'Find more on the website.',4,'AtlantaAero','GBIJYJolkdlXEUL');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (167,155,'Test this.',2,'EZP Bank','frrvyHmwyn3BkLgUmPJplgGpsAoHLCjUFdxET');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (176,164,'Expert mode turned off.',5,'GoodWorks co','72S1wU18bCmVDrTue4HTDDZKhk7yruk');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (179,172,NULL,5,'TrackMedia','Uk6We4INp6zLfo8FqxU3phFoN70mSs6UXgpN0pQMf');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (182,181,'A quick note.',10,'TRPP Transport','pWDXmnwyOtrchsgbA1nBfeLwWcEeoJbdZMUSXcxOhgExS');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (183,191,'Please note the new website.',9,'Kwantum','8pkA5ddlEgxIqukIeA7wpQTbcyzCxJhq3Kr');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (185,192,NULL,6,'TRMM Finance','xze3xe8MuvtTWOK');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (189,194,NULL,4,'PTT Telecom','JYjDPT8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (197,196,'Must verify this entry.',6,'Firefox Communications','TyaG42aTfERZA07C2bGDdqbHNi5eZ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (202,199,'Please note the new website.',5,'Nong Services','Ky4LNLdgwMg4zMVGjJZotec1bHtzsn4Xx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (205,207,'Single mode turned off.',10,'Nunex','goVCGVjXiuDaHUd6QkAcreDL');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (207,217,'Check out their website.',5,'Zatico','PMF6vsWNm5gQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (215,225,'A QUICK NOTE.',8,'Van Houweningen Ass.','UM1QAiJF4Kiy7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (220,229,'Must send an email.',1,'Mecklermedia Corp.','waH66Ujj2KHWj6ASaoR0o6bT0iQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (225,239,'Must send an email.',6,'Van Biesman Accountancy','c0P');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (227,248,NULL,3,'Michelin','1drJ7XenHCGOYgB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (236,249,'Please note the new website.',10,'Able Media','jLgvhqE5U8ulW51m3FPMqM3');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (238,259,'Called 47 times.',1,'NNArchitecture','8U62BJ28VR0c5Q1m6');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (243,265,'Not sure if this is correct.',1,'Scandia','1adF6IdQ6mg5VRL5r');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (247,270,'Read more on the website.',6,'WellPoint','D43NuinrmINwFH4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (255,278,NULL,8,'Numino','onhprKu7CDKJL8I');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (259,287,NULL,4,'ScheringPlough','umxx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (264,295,'Please note the new website.',3,'Create Technology','YVrswsna0aFWERN3GDomjPqaO4NewsOXrtrBY8obmB7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (272,304,'Read this.',2,'JanssenCilag','in1GUtFNjfPjbE56A4HiVRV4ZLyguEzpb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (280,311,'Emailed.',4,'PTT Telecom','J6rRwy76y5GgiVXNc4nX3zeDmvRq');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (286,317,'Please note the new website.',8,'PTArchitecture','F3uRi4xhRHBoWNRtc85');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (291,326,NULL,6,'Martinair','7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (299,334,'A QUICK NOTE.',4,'BVRG Systems','Ricqr01w7zGcf2n44sUCoC2b03KH82kG5cyw16NbLwQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (306,341,NULL,3,'FinlandAir','2R1HVRG1CbBq1H5ayfjazI');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (313,342,NULL,8,'Van Vliesman Constructies','EcD3UCjcGD4617kR');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (320,344,'Still must send an email.',6,'Aegon','GjipGxkqGfYQKbXW0dl3i4SUvpAvKvyYex');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (322,346,'Single mode turned off.',9,'Van Toorn Uitzendbureau','gyhCLJonp1JZmZch7HpQqdDdlaAaVKx6SwPn6egyd');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (328,347,'Checked.',8,'Lederle','Uhns8BElpRkcQHK8SpjNhURg81y1aiFm6m');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (335,357,'A QUICK NOTE.',10,'PSINet','2SWfw6DhG6uvtw46bOEPO2x4Utp3kjKDBjt3UhOFbCM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (339,365,NULL,2,'Peugeot','26WgXO0fYT7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (346,366,NULL,4,'Karwei Bouwmarkt','ZJPFMHphRxyv6T5uEAqGy');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (356,371,'We must investigate this.',1,'Robeco','Ysn8xPt83dj3HyWCstFDlOe');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (359,379,NULL,8,'EX Cooling','ny5mkpjbDAXXmjxQDG');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (369,387,'JUST A NOTE',10,'Catica','X');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (371,391,'Please read this.',6,'Datanamic Solutions BV','M');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (378,392,NULL,4,'Sterling Software','UT3mUuj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (383,401,NULL,10,'LTB','G8pC7pwsXAm41tTerPK4og8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (390,406,NULL,4,'7-Eleven','fGpdBGjPnYcCABUcnO5VfM5UWGyxun7zRPPAQFv');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (396,416,'Still must send an email.',5,'Fenimen','2jvT3qCl8BhX7vYfQbDg');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (404,417,'This is a note.',7,'MerckSharp&Dohme','JJSIiJlWvSQdmlDFr1FIJZJZv');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (407,424,'Still must send an email.',9,'Global Village Communication','WWgtsKZ5jXDDA4Zn5fnpfe5Cx62sApQmEJTcyx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (414,432,'Please read this.',7,'United States Postal Service','XPqcKWmm7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (419,435,NULL,9,'Robot Decora','e');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (422,436,'Expert mode turned on.',3,'UBP Communications','ijiRh');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (423,443,'Note',3,'GoodTools ltd','KqZiDq2R8waaHS3s8jVSXRp');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (430,446,NULL,9,'Van Meten Adviseurs','xJZycKkB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (435,452,'All updates are cancelled',9,'Canon','3jtxn7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (440,461,'Expert mode turned on.',4,'Bencard','l4AoHe');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (447,471,'Still must send an email.',8,'EZ Group','Ojc0Dit8tgszLt0hfhXzFDT0o');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (451,479,'Emailed.',9,'MexxData','4wEGFM43OLnv6Ak4XYq3un53');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (453,485,'Test this.',4,'Batavus','BcVYXuO');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (456,494,'No longer used.',5,'Edu Health','izssh0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (458,476,'Emailed.',3,'ScheringPlough','ArLPQtqULizdZRNZrcc0eIQDLt7tlhZwCQzvI');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (461,480,NULL,1,'BroadVision','oP4iQYu6SFWGeoBJiP4tx0gBWw2xk');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (467,481,'No response.',9,'MioTraining','tvMOdFmqQpBX');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (471,487,'All modifications are cancelled',6,'Postbank Nederland','u6h1XjDHEzuBGdRMlsaahOHQRgBNOZYGpMsJ20Apxu');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,494,'On vacation.',10,'Robot Decora','cEKWQxPwf1Udceey3FSU5K');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,477,'Single mode turned off.',9,'HVM Technics','Y4LJd8rPwTO0Xi6HviQz3KncrGr');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,481,'Note the new website.',9,'Smith Kline&French','S7bpNUWxRjD0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,482,NULL,9,'WAPP Systems','P07n5RgWt3NZ3CXoSTmPNAv1c5783XdTzg');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,488,'Still must send an email.',5,'Mingy Informatix','WUw3O');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,489,'On vacation.',4,'MONY','EvMsQwxlXkayvMexLxdnlDK');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,497,NULL,10,'BVPP Finance','aYByflsOTU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,480,'Single mode turned off.',5,'KM Training','u8ziYcLU7plLyqBUUUdoPeJbZq3to8K0jiL');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,487,'This is not OK.',7,'UR Group','cfHuCKidhR7gFt3vVcfWJoSRh43QgvFF5B7wXj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,494,'Out of the office.',10,'Schneider','hyZoGS83jZ6rWh4rykw2iJ2POlxmERQhmDBNju7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,476,NULL,4,'PTDesign','QuBptNaFjO7otQa5a1MSQIgdft8SaglHE');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,480,'We need to investigate this.',6,'CMG Information Services','8Nv7tmlMlSoL37UjHC7MOR2UDIbJenLfpjX');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,481,'Out of the office.',3,'BBDesign','tNfZx68hAtW4krAfAHVZe6W');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,483,NULL,6,'Wyeth','A5eURd2mjWKSS');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,487,'Please read this.',1,'The Datanamic Group BV','YlYMMn6vugEKsqgUoqotitA2qddV5w');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,488,'No longer in use.',10,'Cszerwinski Informatics','qhPkYiUVXCFH3SyyMGMTt6Ux2');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,498,'Read this.',8,'Seven Days Center','nldcXOViJ4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,478,NULL,1,'Njongy Steel','p2NDqPdDOpSgfsyxMfuIXhYbEhlMBaV3YcFquoA');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,484,'Please note the new website.',5,'Van Biesman Uitzendbureau','MVmWR8Av6a7LO');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,487,NULL,7,'Dacia','SNwanHLIisATT1tEvPe8P1fuUVunvDw2VM8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,496,'Out of the office.',1,'FIAT','HMvym5YCZclalHHhBnVrA4TcdGDW0OHnqoUycZb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,498,NULL,9,'Batavus','oPbDXvgzpnpakCTq1Zi45c');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,477,'All updates are cancelled',10,'Niops Software','67tMLWY');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,481,'Unable to contact.',4,'Itica Transport','ScQrci');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,487,'Unable to contact.',10,'RWIP Works','OD3');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,497,'Please note the new website.',10,'SpainAero','JBVz31fIYWT2bfK5a2wWlTJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,477,'This is a note.',1,'LSP Technics','FxQ04IzAQ6SJVC6cae8ow8kNb6we');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,480,'On vacation.',3,'Fulcrum Technologies','xR7tfZex6HritBsAyf1F');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,487,'All updates are cancelled',4,'SoftQuad International','B3VdpcbKtC3BfxHOTBiWGRys');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,491,NULL,4,'Zeneca','2uiSdKr2HIoGZLV8N8kZByMhWDuu1m3skO6cy1vlcU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,476,'Single mode turned off.',2,'POET','IJjjloZl1YedCVjZOZ5i61mdIKLEkeoSix5KK7PYrT0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,480,'Not sure if this is correct.',8,'Infoseek','EmxCie4oxbMzqDJTY0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,489,'All updates are cancelled',3,'TRNG Systems','HOtSUsNGiZ2VVmRYe0ItlbCRLN6b0noOHqqhYD7Yn7yn');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,493,'Single mode turned on.',6,'CreativeSoft','W7AU1wFEmI5xDRd70rTHaLDHNSFjjYmDO0C5hh');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,496,'Unable to contact.',1,'Beecham','4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,481,'Emailed.',5,'Oracle Corp.','uhLiJph4uSrYL');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,487,'Check out their website.',2,'VarigAero','rSCxTCDZOuN2cwcABMTIHnfnPfiykvpBx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,489,'Called 69 times.',5,'EW Finance','vL02J1CovchXz2Su3g1yU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,499,NULL,5,'Pandata','D2J2qm3CDjpiFKHJBFNBRq8rT5c');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,484,NULL,1,'America Online','asDsQdcUqOVOK7TFiO5r4I4A');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,488,NULL,9,'Branex','YGZ6V');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,490,'Checked.',7,'Next Media','SBx5yaxGCR');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,499,'Not sure if this is correct.',1,'Margriet','QGXubBXD1JCC');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,484,'Not sure if this is correct.',4,'Eetapa Systems','NuZ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,491,NULL,5,'CXW Finance','og04k6dM44FucAbKqYpqRdqHeWEX2wmln0h');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,493,'Called 78 times.',8,'Pfizer','NlWutWEfjKw0clzD0rMrADF4wBBH');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,499,'Checked.',8,'BetterMedia','hvOO');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,478,NULL,6,'Simopix','o8qloXYCGhSmdaVSRdybVjQwwcZ4etLvuR1vY4WqOKoJJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,487,'Called 26 times.',10,'Braca','MjhEoBGFkd6HuiGCZA3IE3iOjsFDusSnabmNA');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,492,'All updates are cancelled',1,'CMG Information Services','kOnL0VH8pG1y8yrenwTmh75gbvTSAEaid6Rca');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,476,'We must investigate this.',9,'Mecklermedia Corp.','NtFE3tvyNM1iWkTZqJyIs1VVWXGm');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,481,NULL,8,'Vardisio','CtvuXiUEXCbytqsv37LPG7fa');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,486,'Called 99 times.',10,'FinlandAir','rZsqqJblBakipLUmIziwalcuccWXEeTm7aUcAVhz');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,494,'Out of the office.',9,'Vredensteijn','08C6IeULi3UVAgAq5N5SngxTPZQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,495,NULL,1,'Van Ooyen Taxi','eNhbDsXzYkdyP6vylMGFRDF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,500,'No response.',5,'Van Steen Beveiliging','fRz1f3vQmBXmRN7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,483,NULL,2,'Ubani Communications','tTyjvGbDCXMW3iMs6cc7VWNnZG5HbN6JPF7SHLhimUeEs');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,493,'THIS IS JUST A NOTE',1,'EADS','6xWKWNEFcaGr0N5RIfhrHs');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,499,'Must send an email.',4,'JanssenCilag','t4JdsWH5UyZBWdd35snmrCtAqvhakQnFU7z');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,477,'This entry is not OK.',8,'Weekamp Deuren','6VTltsPVls3FKpuB3fqNS86KOMhy');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,478,NULL,2,'Lilly','hZ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,488,'JUST A NOTE',8,'Weclo Training','b');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,496,'Emailed.',2,'Van Meten Verzekering','3NSbMJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,498,'Expert mode turned on.',2,'DallasAero','ATSwpGEX7VJLgPoZg7djYEMymzo');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,500,'We must investigate this.',10,'Credit Suisse','LL7SU3dm8IKgTdfal0w7DXCWqANJnbEHnR6Kw');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,477,'Called 29 times.',8,'Mecklermedia Corp.','H3nrEvvEHXwQ5IuyUwgr');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,481,'Single mode turned off.',5,'Milan Bank','8v4o3xhEKTh4WDLUv3aF2S2uszjRUTIvhaqbf1SYew');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,490,NULL,10,'Casco','1clRsQcLS40XOnXhTK4fXL2KLsi0uuEhyL0gC1mTDyUkv');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,496,'Note the new website.',10,'Scandia','5H7iQHxFkSyELCl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,500,'Out of the office.',2,'Bencard','DP7FejtA0Gx8YnFegC4NptpwduRTsRrnDGjjiocpJmK4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,478,'Called 17 times.',4,'M.A.I.D. PLC','J3dnHTvP50isTrnOlLaLrMheqAyrmXYQBLYPuj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,487,NULL,3,'Gamma Holding','C7305Dl8BeUc3Q8t51PTQhixPVbtEl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,494,'Emailed.',4,'VOF De Vlinder','NIBFQ8n7YXq3xmpUTcpj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,496,'We need to investigate this.',8,'Endemol','sVDqooVsdXrwiEPiu0hYcTGGaouGMLJc');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,499,'Single mode turned off.',7,'HSBC','aSOW48ZjOXlcxIXTPKRz7uPlwU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,500,'Test this.',1,'Lilly','xAAywnXJegdSqrENz5oS37rLWl6oQh');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,477,'Read more on the website.',8,'Microput','y2WxVj4n7IN4oAoeXGzrqM3p3WZrybcrgdH0q');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,478,'Test this.',9,'SpainAero','pWZZGKeTmym');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,485,'Not sure if this is correct.',10,'TimesSolutions','eMzX');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,491,'Called 06 times.',8,'Sun Microsystems','tKXx3SCpVTSI80FvVlicZTpqs4IHNOQFz3KhaoLbkyB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,492,'No response.',9,'Ebana Systems','AR4MstQDwgQ00rf0IafOyJpNowzpl8t2vzP');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,499,'JUST A NOTE',1,'Wyeth','HbxX3biDJB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,477,'Emailed.',10,'Boehringer Ingelheim','zV6rctsVDIoo');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,480,'No longer used.',2,'CIBA','cc3kq');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,481,'Still must send an email.',2,'Ascend Communications','hj06x0Hu8ePZpxO15JsmqAd2vpeTva');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,485,'Out of the office.',1,'SoftQuad International','pOb85mVx2jqj8DqheWXuEGWplDhOQQruX');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,493,'Single mode turned on.',7,'Grolsch','0WBMrSU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,476,'Out of the office.',8,'MVG Systems','eb5UTLqIx4POTdhdfrI3fAgbS3NpnzAFLNxVY7Areq8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,483,NULL,6,'DotNet','JBhKtn3zUrNL8oNL141pv4R0KQwt5IuT2rKWBbY0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,491,'All updates are cancelled',7,'Gandalf Technologies','I');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,497,'Note the new website.',7,'BASF','2DAYcltjfBCYHU26uqcS5iOihQbfFrXNQhxRMBJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,479,'Read more on the website.',4,'Van Ooyen Taxi','7YCbGdJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,481,'A quick note.',7,'Laterna Corp.','0ljzoTkQE5HWR0QF3aOniiuRL5F8PE');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,491,'Emailed.',3,'Zincan','Qcx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,493,'Must send an email.',9,'Verity','dq7WBD1UhnSF7k3Z');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,498,'No longer used.',10,'Weekamp Deuren','kJmp8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,499,'All modifications are cancelled',2,'Zaal Buxus','LxCOFagViGvEAAwOnxjTymhsb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,478,'Expert mode turned on.',7,'Trapshop','ZkWENmhHpBroxWbCfTnxQL3Hve8xmQU5');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,482,'Single mode turned off.',2,'SwissAero','r1JTPBzBlnGzjY65G7L5uSoVjDRp0uz5byYpfAg37F');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,489,NULL,9,'Evans','ffLaEQRXVMRr5xF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,492,'THIS IS JUST A NOTE',7,'SAAB','YsqKq0fLR');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,476,'Called 73 times.',8,'Citigroup','pKl43A');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,478,'We must investigate this.',8,'NUDS Communications','Eajzd');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,482,NULL,7,'KV Finance','fBkA0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,483,'A QUICK NOTE.',9,'Heraut Solutions','VasxTPb4AGyod1hveIAzmF7ME508FOZvCrdorQ3u02K');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,485,NULL,10,'Pepp','6lJJFtRLLzBrwi1S0PBoPFXytTzAyioW4GY');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,495,'Called 18 times.',2,'Takita','ESceM7EHwM5417kOIIX8L0vAENvfWxk6H4Jc3');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,479,NULL,10,'BMW','C04DB13mF2E');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,481,'3582',3,'Notalya Consultancy','aA1');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,482,'Read more on the website.',10,'Sun Microsystems','O3evqdm2geob7BzYO7b');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,491,'No longer used.',10,'Telefonica','k');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,499,'Expert mode turned on.',5,'Unisol Paneel','oaNjGwpj4OlpvJ1gjXfrxXPAyaYIp2');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,483,'A QUICK NOTE.',7,'Brinkman BV','RwVXg76ThXGo6NsCVhiC8pd8DdDO6Ae67c82j30x');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,486,'Must send an email.',9,'IDEX','Aax1xAIyoJ4nWyRduMcSBIVdPtul105pWoAemYf7HWu');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,488,NULL,4,'GUO','g6DyHtoZWkNP71QMdinaYv3yeP3J7m1aniNbG60vz5lHc');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,490,'Read this.',9,'NATR Systems','AY4PsZVlHtFN4e3XvXVZK2p2');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,499,'This entry is not OK.',1,'Robot Decora','xlbC8Mo3F4lbNb63P');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,476,'On vacation.',7,'Akwalampa Uniel','VDSe4Qktu13D45eouiP2noRsa6E');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,479,'Must verify this entry.',9,'GreenPoint','YZg7PrgBkgAydn');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,485,NULL,7,'Fina Solutions','IjbCZbbnxpPhAxv0v7YtcgZVLEl6m8suyZp');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,487,'Test this.',9,'Chekfree','EM5eJhLNISK6Dj8EAQ7TrDw5k88iyCZfey3');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,493,'Note',7,'Van Walen Consult','KEaauAK');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,494,'Not sure if this is correct.',6,'Taca','kvlXjqZiMFNlDPfLLjCOey2egS1');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,495,'Not sure if this is correct.',6,'WhiteSoftware','TZMXiBpijpTkZl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,478,NULL,4,'Kovotna Consultants','xSW11p5tIQXiVPgPPYj6OKKoNh8MHiVODIqS');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,485,NULL,4,'Brasserie De Meiden','Hwz');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,488,'We must investigate this.',6,'EB Builders','ZFndrchkTTYzLWxQVwpZZzGr26S3');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,493,'Missed his call.',3,'Sanofi','z');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,494,'Checked.',6,'Super Confex','GNyo276SB6KaGPN31vjIOOgA');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,479,'JUST A NOTE',7,'MossTech','6sDQOTtKw');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,487,'Wating for reminder.',9,'EMI Music','JRmNC0bQnVAPMNLmlsIvZ3EtmTYN4qgxb2HErwAxAiYd');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,497,NULL,3,'Cascade Communications','N');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,476,'Test this.',8,'Cascade Communications','smW86');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,481,'All modifications are cancelled',4,'Imtech','myGIDrRnv8HxcXeN5a34Lmnp5b');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,491,'A QUICK NOTE.',1,'Wang Computers','q0WnOmM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,500,'This is a note.',8,'OCE','inb6OYqj7vr1SsFSKw6nJK');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,476,'Out of the office.',5,'Allen&Hanburys Ltd','zPNEzJsJVuajnXl6Pc0aOiWl4SQ1rVIXSJhG7yEVypH');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,479,'Expert mode turned off.',8,'Lisboa Bank','F7BroeLeSumLkhsEki3RyKcCcrZhoYeiz6gCTgX');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,484,'JUST A NOTE',8,'U.S. Order','HleEgcXemT');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,485,'Just a note.',6,'BVFR Communications','ByRQhjR4eZfBjmOFPLO0aLGSdTINKlcvaywV');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,488,NULL,9,'Innovate Training','w84h3ZCkejuuARII23YMicgLMrNyzyZLsp');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,498,'Missed his call.',6,'Itica Transport','T3MSlGgzzGj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,478,'No response.',9,'RVC Builders','K');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,484,NULL,3,'Siemens DE','2rKViShoZ5QctZOn6eakf6UUiFNgRVZ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,489,NULL,5,'Spyglass','cgTFoITiNGgntByMVcPfMDvwzsaN2A2SmclMgZ87');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,494,'3392',2,'Van Vliet Verzekering','T');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,477,'Please read this.',10,'Innovate Health','t7HmocQuuziM1koS1BwYl5qyqJsj51MrCBB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,486,'Called 64 times.',4,'Van Steen Woonwinkel','omuk5Pd65Sz');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,488,'No longer used.',3,'Heineken','FF410e1Bx1NzbkZiZZGMnaezzIhbkuJkQXhmw');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,494,NULL,5,'GreatWorks','Ed3aX1rQv3QpLwiYxphYZpiRbJYYR1mifELFlOA');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,478,'Check out their website.',6,'Setto Bank','ySdc22mq6KjRYhDRkWMgjxZIpodRQmw');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,481,NULL,1,'Fenimen','eQg0V4zuj7YltS3z0vv3bPCZNfEy76s');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,487,NULL,3,'BASE','Xxx63ZCsrk0bwkpjLTfV8HmFFNMl7Zv1BzQ0IWv');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,497,'Find more on the website.',2,'Peugeot','K');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,476,NULL,7,'Scandia','51LFK2DwhHnjUQ4t');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,482,'Check out their website.',9,'Mlaha Karpa','C6VT6sLXZnQiOSL32X6SpOm8DEpMc6Xu4IOnRkaxpEU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,483,NULL,1,'Van Boschker Accountancy','kbM2warF5l4Arjck83');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,485,'Note the new website.',8,'Les Chanterel','bXsBauhaa');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,494,'Note the new website.',7,'AK Group','vHO8FRKlSiXGCqyIwNyzIR6cLpcokpP5Cafcko');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,498,NULL,10,'KHNG Software','KtdGlitRd4fRNaVi8KtjT6cyN');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,500,NULL,4,'Microput','PLgDOza5QVjYPBt');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,477,'Emailed.',3,'MN Bank','aLPWutikygXKAw3Xdbyj0dc5kM2bpl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,485,'Unable to contact.',6,'Mlaha Karpa','QmRXmIQ6lNKm2QR5SOiQXkaa6yBbWCBVKwYCFoccTdK');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,494,'Please note the new website.',9,'MossTech','MOhp0ovNbaaH8jDyUiG0HfEz14wChyFBgOb0iLne');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,499,'Find more on the website.',10,'SoftQuad International','AoATRAiWsxrnhf');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,479,NULL,5,'Securat Bank','l4YKBhT3eeD4GONmpSZsx1ELZqDxknHBNDw3');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,481,'Find more on the website.',9,'Scholtes Vleeswaren','kbbaCcD2bYXvzmcwKTnoFpoZcn4noJQPh');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,489,'Expert mode turned off.',9,'Open Market','CUn');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,495,'All modifications are cancelled',7,'BeterBed','YyaLshgRdOybn8AxN8CDupAD4SeiHjLaO6gfmMpb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,480,NULL,7,'Excite','OwRJBcBgRXxWEXcwhzja');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,483,'This is a note.',10,'OnlineTools','s');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,486,'Check out their website.',7,'Laterna Corp.','k3c0kdGM6mJRAu3tSrfkmEQwVni4HW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,489,NULL,9,'Zatiflex','ZQbt8q');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,493,'Check out their website.',5,'Allen&Hanburys Ltd','8G6qAkoaeey5ExgsibqrhF3akF6NqNkARgGQriYgmSSHB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,498,'Just a note.',5,'POET','LYkSIH6qegSGejLMgjobNC');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,483,'Check out their website.',10,'GoldConsult','e2zDPz8yhbM5SloOGr02huk0nRKE4dSu01amFu4guCw8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,489,'A quick note.',3,'Fluid Management','uC7B7l8lBUY46QxNeM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,491,'All modifications are cancelled',7,'EADS','jAvVoSV5NMoKLHnLhxlQE5KxW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,476,NULL,4,'Fenimen','EiL4Sx5P8TNxlc62GT3VA1WdBcl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,480,NULL,6,'Kovotna Consultants','iaYb3WK6Tc8O7QhKBUoDL1kHtwPtKeJAxxfT0pmao');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,490,'Must send an email.',9,'Mlaha Karpa','Z5');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,499,'JUST A NOTE',5,'Check Point Software Technologies','WRWYupkEnJoFL');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,476,'Single mode turned off.',5,'Fluid Management','HPfY0OKllmHn30wUn8QXuGy8VoNQ4OP');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,484,'No longer used.',3,'BASE','Xj73TsuLo4EGaUBA7ceTugWP');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,489,'8552',10,'KZX Communications','ZQIMydpYum528g');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,497,'This is not OK.',8,'Cruise Works','ipSTNGc8Niozrb8YXLyx4C53DQ3bNjnrDQOghy5');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,476,NULL,1,'Meinders Meubelen','ZbVy3SVi');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,482,NULL,5,'Roma Bank','HkvzfGp6EVhT');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,490,'A QUICK NOTE.',6,'HJArchitecture','YqiBNUnrdDEnN34RrUPmQVUFzjl0dL5cQMyVrROnZ1fp');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,493,'We must investigate this.',3,'Organon','jFVtAExUmMgKzRC64ZjstcTJGvm');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,495,NULL,3,'Pepsi','7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,496,'Check out their website.',8,'Scholtes Vleeswaren','oKqmLY1');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,477,NULL,9,'MCKL Consultancy','60XPuHEqEWSZt6QczZxDBpwXMDhF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,484,'No longer used.',4,'EuroTools ltd','l8vQlOMU7pnycPpIekp0z');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,488,'Still must send an email.',7,'M.A.I.D. PLC','h1cnhJNgqsdPGreVB7JvNVB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,493,NULL,6,'Cszerwinski Informatics','TPH1XjzRIfa5pHSTmhxB6iX8Joirj0MFOScLE');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,478,'No longer in use.',5,'Fenomen','XRmHlGvqqGrX1J10hxT');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,481,'Test this.',3,'EWIG Communications','70RWrNzKKNWxjxoniRlnDnhJXvTGZL4sNaG');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,483,'THIS IS JUST A NOTE',4,'POET','Z50vmyTiTCM6DeLDjGgE');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,486,'Emailed.',8,'NN Training','TGynBQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,495,NULL,6,'HGDS Communications','lJVvjJoBNhhogkJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,477,'Check out their website.',9,'BBTraining','gjfKBiyjG');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,484,'No response.',6,'HWIG Builders','AUYAYDvqnnTCVU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,490,'This is a note.',8,'PhoenixAero','7wuGxHZ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,500,'Expert mode turned off.',2,'Organon','H2n6H2mEbDDOeWNY7zM5QQItjTWpfMKWLwSHbKA2m');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,484,'Must verify this entry.',6,'Geigy','0OqKdCAJVUzbSFoKC2xUy');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,492,NULL,7,'Bank Labouchere','O8NsLNyyoMu1pcBw4aTwAgp6JLaNGay');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,477,'This is not OK.',3,'Leski Meubelen','aItUxRprpajFl2');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,484,'7378',3,'UV Builders','AfudTRP4hpJbdtdb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,486,'8067',6,'Aloncor Communications','0pbg1JULcRIrc7iUAopXxkM241MwTaqI');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,491,'Please note the new website.',7,'Scholtes Vleeswaren','aPBAt6hBb87jrWehyvBv8V0bGle3PuYvGHvLblQcMD');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,493,'THIS IS JUST A NOTE',1,'Telefonica','v');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,497,'Read more on the website.',4,'OrangeSoft','LNd');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,500,'Emailed.',8,'Pepsi','2ImU5tlDarNisOJJV6GkoxZyklPuwZTERQcLolQi83');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,479,NULL,3,'Symantec','USlbLLQlNemDLCgvZeMkuvrNZzsabQk7ppLijeE');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,487,'Find more on the website.',3,'MONY','ytVu6oC0fdAhbiHkINAiFnczE7kOJEEmEzR7KaC');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,492,'Emailed.',4,'Cascade Communications','Jj06kzHKiL6OXJFFWO');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,499,NULL,5,'BWise','LmBAVYowu4MdEKU5ppdufgt7LMAk1');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,484,'Expert mode turned on.',3,'Free Record Shop','Blhj7YyWaHCfBNUzQNmUOeSYVg');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,486,'Still must send an email.',6,'LQ Group','x1xG0xDowpJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,496,'Just a note.',3,'Kwantum','JCWtbzioFYqYCDR');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,477,'Not sure if this is correct.',10,'Roma Bank','3rqju');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,478,NULL,1,'Fenimen','HTl7nPeMX3NYYvzyqvTLhbADY8hI');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,482,'Missed his call.',6,'Wehkamp BV','GyKJl2f');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,485,'Must verify this entry.',8,'Cybercash','aE');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,487,'Not sure if this is correct.',5,'DallasAero','qeZ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,492,'Find more on the website.',2,'Volkswagen AB','kmNe2Bx3uZZ7YHrLj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,496,'We need to investigate this.',4,'Sterling Software','MKn1uVG4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,478,'Out of the office.',1,'Margriet','X46uNoQSeECuEZTFbRG5UWz0cymNj4QBal');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,480,'Unable to contact.',5,'Firefox Communications','TVIhhdVQPsP55E7REUYhDNMARGkXt8GUr37hWPO');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,483,'Test this.',9,'ShopCentrale BV','1ne534f');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,491,'This entry is not OK.',4,'KVR Food','fmI2ktdHWvtHxp4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,500,NULL,2,'Djongy Oil','NwtEBfXnYGzbOU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,479,'Out of the office.',8,'Firefox Communications','7wAkS8zUAPvJMeKvQIPYiDW5aW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,488,'Single mode turned on.',4,'Secure Computing','ZvlKAYBqcVCfgQDkf45xXpDyAZx16DWO18SE');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,494,'Just a note.',3,'Symantec','QIUjh0uiw0L2MCot');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,495,'Please note the new website.',2,'Turin Bank','ZWqcfA1gDf3nUmvAAIcgmhUyCPA');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,500,NULL,1,'Ethical Generics','lUaxtymhfC3Z1kIIIfuwai4cFbtkjjomEmJFPSFVO');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,478,NULL,8,'RRS Bank','USMV58FiG');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,481,'Unable to contact.',7,'Nongy Steel','QlFJEHrjVwT4OCzbbgQafkLHFKFRkRcXpANQm77mijrx');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,485,'Read more on the website.',5,'Leo','e');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,493,'Test this.',9,'Martinair','GBwTVpNeQITMEXZ4TXJeo8m');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,478,'Test this.',7,'Zjong Oil','5kxxfqkA2V2txXp208Ep3MUGAputZNLaUR0wc');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,479,NULL,5,'Casco','JGy03ihJY7SX01DKhu');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,486,'Test this.',2,'FF Architecture','aiTOMTaxMTXkBHsLzoqrDrbF0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,487,'We must investigate this.',3,'Dotser','YKY75kVm7P');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,492,NULL,6,'Notalya Consultancy','yg0TvfHfmGOBUZk4Atvm2kcNPvGj0K81Tfr506p');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,476,'Wating for reminder.',9,'Spyglass','n1NRe4EfB0Im4EtV7P');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,482,'Read more on the website.',10,'Zaal Buxus','1ZsKzq8uf3D0IWoMphGSt55URDmCgqFhdi7Fy4FU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,486,'Single mode turned on.',10,'BristolMyers','vbcoOdW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,495,'Note',3,'Mumo','z');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,478,'Single mode turned on.',9,'Open Market','ZT4sm2XHGyNYLscepD8NkkYGlWYn344pe4ItU7B2');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,480,'Note',1,'GUITools','zF0yk5PdSUOjlinDuT');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,488,'Called 11 times.',2,'Microsoft','EkZwGbtvagwvSELpFvo5GAoJb7lOz0bAS');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,491,'Wating for reminder.',4,'Van Houweningen Ass.','57TDJpztzG2Z');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,495,'THIS IS JUST A NOTE',6,'Premenos Technology','Cv1P2Ljp');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,478,'Note',5,'Microput','VwEEdIgEuapKVx1Uuk7MmJ15mt02Z3Mxv2hWt');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,483,'JUST A NOTE',2,'AmericaAero','pjjSjHCGltr0t5kCazpHkQMWIFeVs1JPVxCgyoelCoDg');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,486,NULL,7,'EZX Food','gkYMzRCC1iTHdELquQklHl6xpB6');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,492,'Unable to contact.',2,'HGFR Solutions','QM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,496,'Called 22 times.',6,'Abbot','8Wsl8TB1HZirwf54EMsmMeZ2y77OXvr');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,497,'Note',3,'Kovotna Consultants','4xeevMckVRmpiZEhSGs3wcJFc53zJI');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,499,'Emailed.',10,'Imtech','riRBgLRt');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,483,'Out of the office.',7,'Oracle Corp.','YUw6eQPVlKQE7NwcGRBaJubFA');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,490,'Emailed.',4,'C&A','xcDReknep2VPfBwQuTvMwzaXqC7J4AsXWsFQxMV');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,495,'Wating for reminder.',2,'Batavus','SUtmQHljroB8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,478,'Must send an email.',5,'BLogic','LyNji8k1wR8Uve0m817WNWQZfqWf8q786Inq');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,481,NULL,9,'Neerdam Installaties','H0JrDFNIt3vZ6');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,488,'Read this.',4,'Scholtes Vleeswaren','mTliTemd80N6pxF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,491,'Expert mode turned off.',9,'BASE','eR1tEhL');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,492,NULL,5,'Mongo Services','RUWf8zIRQULeJR');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,496,'We need to investigate this.',1,'Vredensteijn','owYSR7sl6YXWif');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,500,'Emailed.',10,'Van Biesman Advies','0dWQfcH85zkdQFiXow7hZkDMp1vXAB8rzkCJp3OkNq');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,483,'No longer used.',3,'VVDesign','Slz1Jqd1iJj55atKEILoSXm87UjhaNg6EDkuC');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,492,'No longer in use.',8,'ERKL Finance','r4W2H0MrB8Wii5iSM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,499,'We must investigate this.',1,'BristolMyers','y4MCgLr5RV4Wolzj0KJ0GsQgV');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,477,'A QUICK NOTE.',7,'United States Postal Service','Us1chVgzVKv26aATdxHj4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,483,NULL,3,'Wyeth','E8NsYj8WzFQBJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,491,'Check out their website.',9,'Super Confex','qJiAu5rCKDhniW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,495,NULL,9,'Bremen Bank','GTJAlDqHcgwf1eFswybpRcJjWjBixYDcLst2icMb2F');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,496,NULL,8,'Taca','ok3pPUXoTSMY23wMybHrBMUEQhpDpCmyUA0ft');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,476,'Read more on the website.',7,'ChinaAir','DFec18OopiOwHd3Rc5oKD86qBpNhz7rug8fa6vTfNZa');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,479,'THIS IS JUST A NOTE',6,'CMG Information Services','j64CSpe5A3dImsE5zPvBMZa');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,482,'Checked.',2,'FIAT','sw4mMr8YdJjcVsRMUlVtmA');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,491,'Checked.',3,'Ulana Computers','BBeCfDqKFP56');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,492,'Not sure if this is correct.',7,'GoodWorks','Lajlwm27iC6YalCn7EN0c7KqsIXca0sq351teCpwW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,495,NULL,3,'Dataware Technologies','BzVKCNtcXWo1');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,480,NULL,1,'Orion','if8tEKmxHq0UqSTi4EbSKwR0ahLG');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,484,'Wating for reminder.',8,'BristolMyers','2egMxmdjpA64NE8croQvpMyCrOtnVYVGpsf');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,488,'Out of the office.',2,'Fortis','VxCmPJ5lrMY16nj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,490,'Checked.',2,'Simopix','d11RD6uDq05j2Nf2xnle0EfB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,495,'Single mode turned on.',7,'PhoenixAero','CQdXwdN8XZKi');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,476,NULL,5,'TRNG Communications','KSCUd20nGHH2nrBPhQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,483,'Expert mode turned on.',5,'PT WebDesign','kVcA3lf7E6vxSE24ztJP8nGfi4Nhj6Q0cUsFK');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,493,'Still must send an email.',4,'Sure Tech','DVFkV5C8DZH5WiqfEla23Bbgj6Pn');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,476,'All modifications are cancelled',2,'Smith Kline&French','HRX1SDxyb1pjpSWeYLH');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,477,'Unable to contact.',2,'Yahoo','fafq0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,485,'Read this.',10,'WhiteSoft','oKqWMRuvMF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,495,'Called 10 times.',4,'DenmarkAir','Izx1rxSKyZbBDr3AVOolPOvYrOnxo6XroU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (495,477,'Called 65 times.',4,'Smith Kline&French','YkuAlB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,479,'Single mode turned off.',2,'WATR Software','qxSupy0HFrpeDNAHPK');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,486,'Must send an email.',1,'America Online','eQmr0PkY57zAWOO');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,491,'A quick note.',1,'RedStone','qUQo7ojMbs6s0KmASNXSVAfjQI');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,498,'Check out their website.',10,'VocalTec','MCkR1QkEAwn5Y');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,478,'Must verify this entry.',2,'Waltman Worx corp','1EyJc0Gw17nzY');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,488,'Still must send an email.',6,'KVW Group','Wwe5DFW2m2MpyNb3mHalQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,490,'We need to investigate this.',2,'Zotonex','gW3e');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,498,'Missed his call.',10,'United States Postal Service','YgMXIgyfdh');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,482,NULL,5,'Cszerwinski Informatics','5U54xZVBx8yxfyKpQoLWJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,485,NULL,3,'Van Ooyen Taxi','uSiOuTwtRvBDBwLpoWfPMEY80XmwlTbug');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,493,NULL,2,'GUO','ZfOka44zgWGKazQBLdAKXYXJQiXK');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,498,'2237',8,'MCPP Consultancy','1sFkt1snuuktfmoWeb6mt7LJfx3N');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,478,'Expert mode turned off.',9,'SAAB','T');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,487,'A QUICK NOTE.',10,'Eloncor Systems','02qmerXtdn3ql3KB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,492,'Single mode turned off.',10,'Ybani Computers','gB4zYLLyNqdtldB4jpHn46AB1eRqe');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,497,'Note',4,'Trapshop','bl1xpnWSo7N4C');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,480,'No response.',2,'Endemol','LjGOYAbCDPwuC3xAZLX6TyopDYIptMFvHFvukgQ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,486,'Missed his call.',3,'Kreitlar Management','WeDCMPF7bB1mcog3rdd8B1MVbqsNGEXayJyZw0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,489,'Checked.',2,'Sherico Consultancy','NhZXjvKMt2y2hm3Es3jZjXMkoY5SM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,497,'THIS IS JUST A NOTE',8,'BMW','x5iE6qaOwq2i1e');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,478,'All modifications are cancelled',7,'Edu Services','yA4ygraeXGeI534OdFv');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,480,'No response.',3,'Silicon Graphics','MdCLUVgWpA5scUazBAcQbqwnXdj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,486,'Out of the office.',8,'CMG Information Services','z4D60dWnPcYBtGmZt1e6vKITEySOgU5Us');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,488,'Expert mode turned on.',7,'Secure Computing','xF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,496,'All modifications are cancelled',7,'Vardisio','NPHp0ZtZytcHrprUAS');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,481,'8823',4,'Bayer','ZJ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,484,'Not sure if this is correct.',8,'Djong','Nhh5wgCx3BLEEpIryylRr1xtCzoqino4FRZ');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,485,'Expert mode turned off.',6,'Peugeot','iycnghDMvMB7aY0TbmRInT');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,488,'Please note the new website.',1,'Open Text','o2T2VTcWrbWw7epTJShFj');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,493,'Note',10,'Casba','xbAEwE5xsb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,477,NULL,6,'HJWebDesign','U');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,486,'Must send an email.',10,'Cisco Systems','pO6YYYMUEiJU6ckZyzMqnq1e2JgRR');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,495,NULL,10,'Zinco','6uosM2UPjC');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,499,'Single mode turned off.',6,'Zaragoza Bank','LUYDZlv1jFCcUYmNwFkDa6pe');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,484,NULL,7,'Citigroup','q86x7bagN7V');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,488,NULL,8,'System U','Xxz1fys423ZsTa0oYWSEyeoVBQmZFMT32sL');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,496,NULL,3,'Zotoco','Uq');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,499,'Test this.',4,'Sapanda.com','ulUBTLBpNh');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,483,'Read this.',5,'Batavus','qte');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,491,NULL,7,'Ytapa Tech','pqC2W34jHI0oK1kfANMWStYq4MKklKEW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,476,'No longer in use.',1,'Meinders Meubelen','1mhYMKdW6uLqjJDBOMiiNXqyVqvrCT4gyrVzhUjF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,477,NULL,8,'SwissAero','uUm5uGjPLeepA48NaENt068aV1fM3JYdf7QVVUpfGlMXT');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,481,'Must verify this entry.',7,'Free Record Shop','tuZYkibwvO5G8Uzm4BFudaMF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,488,'A quick note.',9,'Check Point Software Technologies','bHmq8wGblBTvrIZnMFBdcRQDRnhXG1C03qIW5iTUqlwmb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,497,NULL,7,'VocalTec','IdGWVHdhrWqFtDNZlSBb81Eq2E6SU2CsMB');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,477,'No response.',7,'BrownShopToGo','XXnkcEZPhHuDEpGrpSW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,483,'All updates are cancelled',9,'Gamma Holding','0yMDwTznkWqL10RxpzYQHG');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,489,'Wating for reminder.',9,'Van Waal Adviseurs','gl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,493,'Read more on the website.',6,'Goldman Sachs','VGNMjZHEp7d3ekN8SmMqiH');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,476,'A QUICK NOTE.',6,'AK Group','B5VWlJ7XwMXh6mw2n7Fj54vBSqoFExLR');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,486,'No longer used.',1,'Able Vision','eXoElCYIzxTMT5r7MV');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,487,'Must verify this entry.',4,'Scandia','PcdwryrDC3QOKz');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,496,NULL,3,'Cisco Systems','fLqvEu70AHc88FFxF7HcoNxCshjamH0opzJI');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,478,'Not sure if this is correct.',6,'Gamma Holding','s');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (488,486,'All modifications are cancelled',10,'ParkeDavis','MFBvqg');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,493,'Please note the new website.',2,'BLogic','b');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,476,'Expert mode turned off.',8,'Squibb','O');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,481,NULL,8,'IDEX','YJRoQzOU8wvL7kCQB0r7ijrzVqH0GjVObRjclwx8Wye');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,490,'No longer used.',5,'MetLife','f5OocGgRa5P4lEh4xpAVEyaSDnGU8fbS');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,499,'No response.',9,'OCE','yx13ju0BfOabDezgRdjJo8rtu1H2iXWmbOa');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,500,NULL,8,'MKKS Communications','Tqq2GP');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,484,'Read more on the website.',2,'Endemol','bK4BgAdGnCrG2I05NHVeqY');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,486,'Unable to contact.',1,'EMI Music','A1aGPAewFFtt1utSRPA6hFfBhWhwku5');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,495,'Just a note.',5,'Njongy Media','Pwyg');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (491,500,'We must investigate this.',5,'U.S. Robotics','ES5zmDhGwqvcRROt');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (497,480,'THIS IS JUST A NOTE',10,'Unisol Paneel','cYW8ZAOSTo334Q');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,486,'Checked.',5,'Van Vliesman Adviseurs','WaEpr1MQ2ZEWAO7vDoDQU');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,495,'All updates are cancelled',1,'Free Record Shop','eAGWjyViMIFzsCKXuc1ua4qP1ZoVt1');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,477,'Not sure if this is correct.',8,'Squibb','Fc8azUKWUHFMNVVB3g1GsT4rpjcUrasWDyRvdqg2nM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,485,NULL,8,'Storks & Partners','YE3gWxo');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,489,'Please note the new website.',9,'Les Chanterel','vUDIY1');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,490,NULL,8,'NUKL Solutions','dIkkmUCh8mdROy6NnzJM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (483,491,'Find more on the website.',5,'OrangeSystems','E1BeDdu3MsP5bv0y2PrSGnZX84a8GCBW');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,497,'Checked.',10,'SilverStone','6yLuLLdcVqrcxwtdsO2c');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,500,'A quick note.',10,'Gandalf Technologies','cm8p6RAeUAvtICeo8O1q40UL4DMLLeqdtpEjSjd4xDgH0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (477,483,'Single mode turned on.',10,'IDEX','le3TPl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,491,'All updates are cancelled',8,'WecloWebDesign','5GXwDFMN7nFAIsrbrwjqYNR1fLNVbLUUBPNVqFsDIyG');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,496,'This entry is not OK.',5,'Mlaha Karpa','AmloOFiCg5S2Oo7Dd1Un');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,498,'Find more on the website.',4,'Atalanka','eTtvK501b5kVXX1rCqzqi4ZsNC3oEe1uW5DgobVG5');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (481,479,'Just a note.',5,'Njongy Services','8ZY5h63tEjr0U1pPE7GDE5Q8Yy');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,485,'Just a note.',7,'TDK','GqlmxznEzxtCCNCHcugoX228fF');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,493,'All updates are cancelled',2,'Aerial Survey','y');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,496,'Expert mode turned on.',4,'WhiteSystems','jGpqGi8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (487,499,'Just a note.',1,'Firefox Communications','LX2kGVgcAkFacPSBDw');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (496,483,NULL,9,'TRDS Communications','AsmQlcWsJA7p1JbbqX7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,487,'Unable to contact.',8,'Spyglass','UU7epaIgt');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (499,495,NULL,5,'IDEX','QWM5');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,500,NULL,2,'EQ Data','ExeCvcGYJRQ8X0aP6Ev803KZcPnL1h7zfnXl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,476,'Out of the office.',10,'Nokia','V4NWbeF1401ZQHFGkFv');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (493,486,'Single mode turned off.',9,'Glenwood','NTcHkf4dwTJnmEL6ii');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,496,'JUST A NOTE',1,'Excalibur Technologies','mro4');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (500,498,'Called 98 times.',10,'Tesco','xXAZtvD3WFJvwwVm');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (480,480,NULL,9,'BB Architecture','OUCO2RaM3dWP');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (485,488,NULL,8,'WecloWebDesign','jmrGTiwubu0XWMxLNTR3x5BDci7VX4QYWCTRiayuSc8');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (492,498,'Find more on the website.',6,'CNP Food','1XVdtHULlk');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,482,'Expert mode turned off.',7,'Cszerwinski Informatics','XHl2s02M7xtZqetVRB31B2VvZe2QXbkGItmM6nhVe');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,484,'All updates are cancelled',6,'Milan Bank','MNQGtonsm2A0J5PZM0KwfgJ3iIRDyadXOuo7ulRwr3L');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (484,491,'A QUICK NOTE.',10,'InnovateData','bHpfRM44HTOG8IR44kv6A');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (490,500,'Not sure if this is correct.',7,'VVWebDesign','Q7');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,485,'Wating for reminder.',4,'Leo','EidGwJFv745r3J1Qz6Hf4DT587');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,495,'Note the new website.',2,'3Com','SjGwTJd6Z1');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (478,496,'Single mode turned on.',1,'Open Market','QGh7sS6pKwUumVC3lD0HdzwyZvpl7gPHp');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,500,'Called 71 times.',7,'Van Sterkendam Woonwinkel','mV2FAPhCGQjoQsMNU6Ac3mKvHZMm1rjXohSE5KzpVl38');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (482,481,'Test this.',6,'Braflex','chO5CZM');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,491,NULL,10,'Van Boemel Uitzendbureau','TK1JbIgqECd6Plo');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (494,494,NULL,1,'Trinity','xBgAHV8skasy06FkWe');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (476,500,'Expert mode turned on.',8,'MCDS Solutions','Uxd0');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,477,'We need to investigate this.',2,'NIBC Bank','WNJschb');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (489,484,'JUST A NOTE',1,'Fulcrum Technologies','7eo5y47h27rj1tLIPSuTaPI00XLY3dX');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (498,489,'9989',4,'Mongo Informatix','xp72vBBr2Y33JxSR8vA3NoAE6GJX');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (479,490,'On vacation.',7,'U.S. Robotics','HFDFVIN2aBOT0Fld6Hequqfeo6TFl');
INSERT INTO "public"."supply_order" ("ingredient_id","transaction_id","comments","quantity","supplier_name","units") VALUES (486,498,'Read this.',5,'KZX Tech','1kjhFVbgfRp4gJPByrv8gGQNXvOmu4pYlkMb2gf4V');
