
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (1,6,'Description number 0518735','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (2,10,'Description number 2369025','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (3,4,'Description number 1421323','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (4,10,'Description number 9544368','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (5,2,'Description number 6271991','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (6,6,'Description number 6867737','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (7,4,'Description number 7631408','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (8,2,'This is a description 8698801','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (9,4,'Description number 9342188','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (10,10,'This is a description 6281108','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (11,4,'Description number 2286148','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (12,6,'Description number 1910985','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (13,10,'This is a description 2813424','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (14,6,'Description number 7918319','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (15,4,'Description number 0631425','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (16,2,'This is a description 5576161','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (17,4,'This is a description 7292692','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (18,2,'Description number 0511759','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (19,2,'Description number 7634221','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (20,2,'This is a description 2806199','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (21,2,'Description number 2777071','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (22,10,'This is a description 4047308','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (23,10,'This is a description 0632852','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (24,4,'This is a description 4800512','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (25,4,'This is a description 8554124','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (26,6,'This is a description 4061572','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (27,2,'This is a description 0510449','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (28,2,'This is a description 7500640','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (29,2,'Description number 6244136','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (30,10,'Description number 3330438','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (31,4,'This is a description 4183184','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (32,2,'This is a description 2274044','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (33,10,'Description number 6863173','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (34,6,'This is a description 7360557','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (35,4,'Description number 6684522','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (36,4,'This is a description 1825844','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (37,2,'Description number 1972723','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (38,6,'Description number 5829090','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (39,2,'This is a description 5083985','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (40,6,'This is a description 8268687','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (41,10,'This is a description 5346208','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (42,2,'This is a description 4313253','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (43,6,'Description number 5350967','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (44,10,'This is a description 5331711','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (45,2,'This is a description 8501683','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (46,4,'This is a description 0886518','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (47,2,'This is a description 9774195','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (48,6,'This is a description 4220701','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (49,4,'Description number 6105901','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (50,10,'Description number 8937771','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (51,6,'This is a description 1444216','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (52,10,'This is a description 0841616','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (53,6,'Description number 0750297','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (54,10,'This is a description 0481688','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (55,4,'Description number 3429743','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (56,4,'This is a description 8691680','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (57,2,'This is a description 8386653','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (58,6,'Description number 4199532','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (59,2,'This is a description 7393875','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (60,2,'This is a description 2383550','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (61,2,'This is a description 7249504','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (62,2,'Description number 9931588','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (63,2,'This is a description 7698872','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (64,2,'This is a description 3956650','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (65,2,'This is a description 2369082','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (66,4,'This is a description 5628049','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (67,6,'This is a description 1004395','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (68,4,'This is a description 2574076','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (69,10,'This is a description 9520659','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (70,2,'This is a description 0781109','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (71,4,'Description number 0349936','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (72,10,'Description number 9691286','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (73,6,'Description number 1319282','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (74,10,'Description number 8526200','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (75,6,'Description number 8884429','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (76,10,'This is a description 4425786','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (77,4,'This is a description 9693566','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (78,2,'Description number 6158897','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (79,6,'This is a description 6245424','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (80,6,'This is a description 8004653','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (81,4,'Description number 0257182','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (82,10,'This is a description 9277147','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (83,2,'This is a description 2287638','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (84,2,'This is a description 0675937','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (85,4,'This is a description 0344161','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (86,4,'This is a description 7889200','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (87,2,'This is a description 1775436','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (88,4,'This is a description 7324737','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (89,2,'Description number 4983981','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (90,6,'This is a description 3745270','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (91,10,'Description number 6747322','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (92,4,'Description number 1645562','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (93,6,'Description number 9997169','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (94,6,'Description number 5896430','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (95,10,'This is a description 4266102','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (96,2,'Description number 9817034','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (97,10,'This is a description 5832490','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (98,4,'Description number 4013638','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (99,4,'Description number 6588357','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (100,10,'Description number 3437081','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (101,10,'Description number 2670964','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (102,2,'Description number 5877185','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (103,10,'This is a description 6045204','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (104,4,'This is a description 3307606','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (105,2,'This is a description 2553493','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (106,10,'This is a description 8704262','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (107,4,'Description number 7536360','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (108,10,'This is a description 2968813','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (109,4,'This is a description 1825465','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (110,2,'Description number 4807195','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (111,6,'This is a description 8274641','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (112,6,'Description number 2174175','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (113,4,'This is a description 7259908','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (114,4,'This is a description 3974919','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (115,4,'Description number 5858515','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (116,2,'Description number 8008481','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (117,10,'This is a description 3596556','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (118,4,'Description number 1185666','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (119,2,'Description number 1049095','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (120,10,'Description number 1406799','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (121,2,'Description number 6459991','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (122,2,'Description number 0149137','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (123,4,'This is a description 3889841','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (124,10,'This is a description 8418826','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (125,10,'Description number 9795767','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (126,4,'This is a description 6201843','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (127,10,'Description number 0781275','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (128,10,'This is a description 5499103','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (129,4,'Description number 9323737','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (130,6,'Description number 1064158','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (131,6,'Description number 2371483','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (132,10,'This is a description 5159481','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (133,10,'This is a description 8927948','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (134,4,'Description number 2654939','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (135,4,'Description number 1690796','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (136,10,'Description number 9315587','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (137,4,'This is a description 8445233','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (138,4,'Description number 7759484','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (139,6,'This is a description 3186881','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (140,6,'This is a description 8673915','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (141,10,'Description number 4422710','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (142,6,'This is a description 4511574','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (143,2,'Description number 7854071','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (144,10,'Description number 7730689','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (145,2,'This is a description 6553274','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (146,4,'This is a description 4690445','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (147,2,'Description number 5674659','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (148,10,'Description number 5374943','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (149,6,'This is a description 3359381','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (150,2,'Description number 2805015','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (151,6,'This is a description 8999256','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (152,2,'This is a description 7918258','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (153,4,'This is a description 1418578','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (154,4,'Description number 8627826','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (155,4,'This is a description 9220825','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (156,10,'This is a description 0277616','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (157,6,'This is a description 3832389','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (158,2,'This is a description 1930866','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (159,2,'Description number 7139623','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (160,6,'Description number 0148502','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (161,2,'Description number 9243551','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (162,4,'This is a description 8802236','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (163,4,'This is a description 4588617','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (164,6,'This is a description 5208983','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (165,2,'This is a description 6598897','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (166,2,'This is a description 8715817','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (167,10,'This is a description 6584745','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (168,6,'This is a description 2533900','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (169,6,'This is a description 8302772','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (170,10,'This is a description 6453259','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (171,2,'Description number 1418819','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (172,2,'Description number 8923091','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (173,6,'Description number 2652545','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (174,2,'This is a description 6677248','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (175,4,'This is a description 7368182','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (176,4,'Description number 8635570','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (177,10,'This is a description 2237938','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (178,6,'This is a description 8951589','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (179,4,'Description number 2444721','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (180,2,'Description number 3428409','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (181,2,'Description number 3913973','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (182,2,'This is a description 8767588','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (183,10,'This is a description 2205213','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (184,2,'This is a description 6536788','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (185,10,'Description number 6448811','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (186,10,'This is a description 2651022','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (187,6,'This is a description 3938920','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (188,10,'Description number 1621348','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (189,2,'Description number 1117310','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (190,4,'Description number 6194094','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (191,2,'This is a description 3644528','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (192,10,'This is a description 1193623','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (193,2,'This is a description 0257866','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (194,2,'Description number 3102271','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (195,4,'This is a description 2350473','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (196,2,'Description number 4781740','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (197,2,'This is a description 0154583','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (198,4,'Description number 6306758','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (199,6,'Description number 1691999','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (200,10,'This is a description 7997100','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (201,2,'This is a description 6939925','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (202,4,'This is a description 9965746','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (203,6,'Description number 5676817','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (204,2,'This is a description 7520858','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (205,4,'Description number 8652732','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (206,10,'This is a description 5203592','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (207,2,'Description number 5614619','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (208,2,'This is a description 5594983','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (209,6,'This is a description 6834848','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (210,2,'Description number 5234955','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (211,10,'Description number 8077170','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (212,4,'This is a description 3270305','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (213,2,'This is a description 3688981','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (214,10,'This is a description 9611934','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (215,10,'Description number 0500191','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (216,10,'This is a description 1519293','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (217,2,'This is a description 5773979','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (218,2,'Description number 2927082','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (219,10,'This is a description 4515974','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (220,2,'This is a description 0716513','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (221,4,'Description number 5897404','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (222,4,'Description number 0989267','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (223,2,'This is a description 0675177','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (224,6,'This is a description 2841171','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (225,10,'Description number 1178975','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (226,6,'Description number 4888444','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (227,6,'Description number 1325060','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (228,2,'This is a description 7977750','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (229,2,'This is a description 5390206','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (230,10,'This is a description 5099380','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (231,10,'Description number 7172242','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (232,4,'This is a description 3742321','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (233,6,'This is a description 5736896','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (234,10,'This is a description 4873322','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (235,10,'This is a description 1323003','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (236,10,'Description number 9231874','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (237,2,'Description number 3573518','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (238,10,'This is a description 9857005','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (239,10,'Description number 2486514','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (240,6,'Description number 3573539','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (241,2,'Description number 2071713','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (242,4,'Description number 8292780','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (243,2,'Description number 5998903','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (244,2,'This is a description 3858918','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (245,10,'Description number 5643543','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (246,10,'This is a description 4017689','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (247,10,'This is a description 0147483','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (248,4,'This is a description 9290184','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (249,10,'Description number 9954333','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (250,2,'This is a description 4036322','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (251,2,'Description number 5439797','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (252,6,'This is a description 8057565','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (253,6,'This is a description 7577349','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (254,4,'This is a description 1694037','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (255,4,'Description number 9631786','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (256,2,'This is a description 0688488','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (257,6,'This is a description 7930669','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (258,6,'This is a description 5465647','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (259,2,'This is a description 9368338','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (260,2,'Description number 3828198','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (261,10,'This is a description 8532662','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (262,10,'This is a description 3757769','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (263,6,'This is a description 0387951','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (264,10,'Description number 2349971','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (265,6,'Description number 4089399','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (266,6,'This is a description 0260023','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (267,6,'This is a description 6848806','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (268,6,'This is a description 5181623','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (269,6,'Description number 9155819','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (270,2,'This is a description 4355694','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (271,2,'This is a description 0439469','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (272,10,'Description number 7368801','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (273,6,'This is a description 7755246','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (274,10,'This is a description 2055959','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (275,6,'This is a description 9613273','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (276,2,'Description number 6266113','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (277,2,'Description number 2237011','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (278,4,'This is a description 3447147','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (279,6,'This is a description 6014139','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (280,6,'Description number 1909373','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (281,6,'Description number 4649108','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (282,2,'This is a description 5747560','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (283,10,'This is a description 3850207','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (284,4,'Description number 7065354','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (285,6,'This is a description 4504251','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (286,10,'This is a description 6423065','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (287,10,'Description number 8392248','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (288,10,'Description number 0514359','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (289,10,'This is a description 0439247','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (290,2,'Description number 3057378','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (291,6,'This is a description 9618158','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (292,2,'Description number 2084054','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (293,10,'Description number 4474079','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (294,2,'This is a description 4089481','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (295,4,'Description number 7541630','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (296,2,'This is a description 4292540','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (297,2,'Description number 7156490','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (298,10,'This is a description 5804563','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (299,2,'Description number 0801560','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (300,6,'This is a description 3146544','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (301,10,'This is a description 3702339','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (302,10,'This is a description 0976098','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (303,10,'Description number 4546027','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (304,2,'This is a description 1129124','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (305,10,'This is a description 5233138','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (306,10,'Description number 6925449','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (307,6,'Description number 7809561','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (308,10,'Description number 1015003','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (309,2,'This is a description 1798869','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (310,4,'This is a description 7818645','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (311,4,'Description number 5419612','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (312,2,'Description number 2009241','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (313,2,'Description number 3048214','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (314,6,'Description number 9521935','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (315,6,'Description number 9518881','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (316,2,'Description number 7682894','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (317,4,'Description number 0995112','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (318,10,'This is a description 4624268','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (319,4,'This is a description 3439012','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (320,2,'Description number 4891568','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (321,4,'Description number 3268192','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (322,6,'This is a description 1407755','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (323,2,'Description number 7383343','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (324,10,'Description number 0209822','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (325,4,'Description number 1101232','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (326,2,'This is a description 9559086','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (327,10,'Description number 3016760','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (328,10,'This is a description 2710727','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (329,6,'Description number 7493771','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (330,6,'This is a description 9868810','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (331,10,'Description number 2139702','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (332,10,'Description number 5363925','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (333,2,'This is a description 2856948','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (334,6,'Description number 3477484','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (335,6,'Description number 3234839','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (336,2,'Description number 1758367','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (337,2,'This is a description 1046352','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (338,6,'This is a description 5796459','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (339,6,'Description number 7819066','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (340,4,'Description number 4976137','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (341,6,'This is a description 6217012','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (342,6,'This is a description 4568925','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (343,6,'This is a description 9892038','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (344,10,'This is a description 8852603','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (345,4,'Description number 3072069','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (346,4,'Description number 0330640','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (347,6,'This is a description 4224476','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (348,4,'This is a description 6005832','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (349,2,'Description number 6048567','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (350,6,'Description number 1056464','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (351,4,'Description number 0310647','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (352,10,'Description number 0730819','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (353,4,'Description number 9644477','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (354,10,'Description number 2858886','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (355,4,'Description number 2645562','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (356,2,'Description number 0730751','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (357,2,'Description number 2412569','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (358,4,'This is a description 1349468','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (359,6,'Description number 7978848','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (360,4,'This is a description 4674566','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (361,6,'This is a description 1571541','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (362,4,'Description number 6775799','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (363,6,'Description number 4780830','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (364,6,'This is a description 9856476','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (365,2,'Description number 3099293','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (366,2,'Description number 6975345','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (367,10,'Description number 1789589','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (368,6,'This is a description 1191963','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (369,6,'Description number 9247482','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (370,10,'This is a description 2823574','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (371,2,'This is a description 0044194','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (372,10,'This is a description 2006518','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (373,2,'This is a description 7765352','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (374,6,'This is a description 3046653','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (375,10,'This is a description 4033859','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (376,2,'This is a description 8033753','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (377,2,'This is a description 0807856','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (378,4,'Description number 5389010','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (379,4,'Description number 1066815','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (380,2,'This is a description 4767286','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (381,10,'This is a description 1378280','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (382,10,'Description number 6397727','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (383,6,'Description number 2804471','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (384,6,'Description number 5408184','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (385,2,'This is a description 0069413','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (386,4,'Description number 4994266','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (387,4,'Description number 1876634','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (388,2,'Description number 1622299','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (389,2,'This is a description 8141165','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (390,10,'Description number 9484602','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (391,6,'This is a description 2521996','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (392,6,'This is a description 7330148','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (393,4,'This is a description 1699414','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (394,6,'This is a description 6741518','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (395,4,'Description number 4988361','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (396,2,'Description number 7335416','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (397,6,'Description number 6123052','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (398,10,'Description number 3043409','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (399,2,'Description number 9048360','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (400,6,'This is a description 7853503','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (401,4,'This is a description 2079301','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (402,6,'Description number 1279238','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (403,4,'This is a description 3666512','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (404,2,'Description number 5160528','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (405,10,'Description number 4539455','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (406,2,'Description number 8325469','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (407,10,'This is a description 5884231','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (408,2,'This is a description 9544750','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (409,2,'Description number 9235601','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (410,2,'Description number 9548754','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (411,4,'This is a description 9757366','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (412,10,'Description number 6482956','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (413,4,'Description number 9578164','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (414,4,'This is a description 4573529','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (415,10,'This is a description 6085554','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (416,2,'This is a description 5137206','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (417,4,'This is a description 4966350','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (418,10,'This is a description 4881902','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (419,2,'This is a description 7163073','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (420,6,'This is a description 0032852','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (421,2,'Description number 2453829','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (422,6,'Description number 2667263','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (423,4,'Description number 3811867','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (424,4,'This is a description 5570760','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (425,2,'This is a description 9925434','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (426,2,'This is a description 6097040','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (427,4,'Description number 2929699','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (428,10,'This is a description 7120620','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (429,10,'This is a description 2618979','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (430,2,'Description number 8888388','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (431,10,'Description number 5325327','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (432,6,'This is a description 7727304','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (433,6,'Description number 1695455','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (434,6,'This is a description 7828079','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (435,10,'This is a description 0979550','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (436,4,'Description number 7543427','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (437,6,'This is a description 3499647','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (438,6,'This is a description 3332500','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (439,2,'Description number 4732514','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (440,2,'Description number 8102785','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (441,2,'This is a description 5184108','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (442,6,'This is a description 2388246','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (443,10,'This is a description 3376021','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (444,6,'This is a description 2241271','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (445,10,'This is a description 3663597','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (446,10,'Description number 2357199','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (447,2,'Description number 3030880','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (448,4,'Description number 6781047','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (449,6,'This is a description 2857923','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (450,2,'Description number 3759642','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (451,6,'This is a description 3561659','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (452,6,'This is a description 8511991','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (453,4,'Description number 5893127','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (454,10,'Description number 6409540','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (455,6,'This is a description 5407865','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (456,2,'This is a description 2846528','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (457,2,'This is a description 9680922','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (458,6,'This is a description 5633824','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (459,10,'This is a description 3624292','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (460,6,'Description number 5876657','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (461,6,'Description number 2363926','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (462,6,'Description number 6394303','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (463,10,'This is a description 5959159','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (464,10,'Description number 4188897','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (465,2,'Description number 7421868','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (466,4,'This is a description 0525459','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (467,10,'This is a description 6607625','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (468,6,'This is a description 4966106','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (469,6,'This is a description 8757060','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (470,2,'This is a description 2543111','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (471,10,'This is a description 6787184','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (472,6,'Description number 5626482','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (473,10,'This is a description 8692681','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (474,10,'This is a description 6522152','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (475,6,'This is a description 4341769','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (476,6,'This is a description 6433730','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (477,6,'This is a description 9622285','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (478,6,'Description number 3073786','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (479,10,'This is a description 8637012','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (480,2,'Description number 2502107','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (481,6,'Description number 2268481','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (482,2,'This is a description 6199495','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (483,6,'Description number 6662716','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (484,10,'Description number 5556778','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (485,2,'Description number 0570911','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (486,6,'Description number 8049722','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (487,4,'Description number 1254593','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (488,10,'This is a description 0710797','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (489,6,'This is a description 5809615','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (490,4,'Description number 3597120','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (491,4,'This is a description 8184122','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (492,6,'This is a description 8684685','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (493,4,'Description number 5901361','occupied');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (494,10,'Description number 9648565','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (495,10,'This is a description 8291506','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (496,4,'This is a description 9209963','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (497,6,'Description number 0641738','empty');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (498,10,'Description number 5802366','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (499,6,'This is a description 4479050','out of order');
INSERT INTO "public"."tabless" ("table_id","capacity","table_description","current_status") VALUES (500,2,'Description number 8623008','occupied');